yolo_model:

  config_file:
    name: yolov3-cai-tiny.cfg
  weight_file:
    name: yolov3-cai-tiny_final.weights
  threshold:
    value: 0.5
  detection_classes:
    names:
      - screws_100219
      - screws_109578
      - stick_101350

